### ISSUE TITLE
The general logic of the demo

### ISSUE THREAD

**Issue by leftsider123** [wrld3d/ios-api#11]
HI Team
  We want to realize the iOS Moving map  POI add and remove effect like demo,  could you tell me the iOS interface can be meet?

**Comment by tim-jenks** [comment]
Hi @dululu522 - we have a new release of the iOS API due imminently - next couple of weeks - this will make the use and functionality of our iOS API much easier and more obvious, including SDK documentation and SDK samples similar to our android-api and eegeo.js.

You can see progress in the ios-api-host branch.

I've marked this question ready for 1.1 release.

**Comment by tim-jenks** [comment]
Closing as additional features requested are captured in #14
