### ISSUE TITLE
float radius = (renderCamera.GetAltitude() * Eegeo::Math::Tan(renderCamera.GetFOV()));

### ISSUE THREAD

**Issue by leftsider123** [wrld3d/ios-api#12]
float radius = (renderCamera.GetAltitude() * Eegeo::Math::Tan(renderCamera.GetFOV()));
Oc has a corresponding API?

**Comment by calumleask** [comment]
Hi @dululu522 - it looks like you've taken this code from https://github.com/eegeo/eegeo-example-app/blob/master/src/Search/SdkModel/SearchQueryPerformer.cpp#L21
Are you trying to find a suitable radius to use for a search service? If this is the case, you could consider using a hard wired value for now.

**Comment by leftsider123** [comment]
Write a hard the value of the search result is bad, there is no corresponding oc version of the API likeeegeo-example-app?

**Comment by jonty-dawson** [comment]
Hi - could you explain what you are trying to achieve please?
Are you trying to display search results on an eeGeo map using the Objective-C ios-api?

**Comment by leftsider123** [comment]
Hi-
I want to like float radius = (renderCamera GetAltitude () * Eegeo: : Math: : Tan (renderCamera. GetFOV ()));This method based on the current to determine the search radius of the lens？
