### ISSUE TITLE
ios run error

### ISSUE THREAD

**Issue by yuxingxing1988** [wrld3d/ios-api#3]
I use ios-sdk do demo, but in the use of an error, as follows:
    When creating an EGMapView, an error occurs in the AppHost constructor. The cause of the error may be that apikey, screenProperties are both empty and have no value. But before executing the "Eegeo :: Config :: PlatformConfig config = Eegeo :: iOS :: iOSPlatformConfigBuilder (App :: GetDevice (), App :: IsDeviceMultiCore (), App :: GetMajorSystemVersion ()). Build ();" There is a value

     We are expecting a reply！

**Comment by jlunderwood** [comment]
Thanks for your interest in our maps!  It sounds like the api key supplied may be incorrect or in the wrong format.

If you log in to http://www.eegeo.com/developers/apikeys/, your API keys are shown in the "API Token" column.  You should create a token for each application, including the example.  The API token should be added to eeGeoApiExample-Info.plist as it appears, without quotation marks, replacing the placeholder text ${EEGEO_API_KEY}.

I hope this resolves your problem.  If not, can you tell us more about what error you are seeing?

**Comment by yuxingxing1988** [comment]
Api token has been set, and the code has also been acquired api token, after executing "Eegeo :: Config :: PlatformConfig config = Eegeo :: iOS :: iOSPlatformConfigBuilder" Api token is empty, and then in the AppHost.cpp Execute "m_pWorld = new Eegeo :: EegeoWorld ",when the following error occurred:
2016-11-24 10: 30: 18.191354 map [2627: 744366] Metal API Validation Enabled
2016-11-24 10: 30: 18.253804 map [2627: 744366] V.1.0 (1)
Map (2627,0x1b078bc40) malloc: *** error for object 0x10141e1c8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug


Thanks !

**Comment by jlunderwood** [comment]
Can you help me understand your setup in more detail?  In particular, are you using the eeGeo CocoaPod directly, as shown in https://github.com/eegeo/ios-api-example#getting-started ? This example shows a simple app using our map and is a good place to start.

The instructions at https://github.com/eegeo/ios-api-example#contributing are only required if you wish to contribute to the iOS API.  These instructions are not required if you simply want to use the API -- you can just use the CocoaPod for that.

If you let me know how you are including our API it will help us find out what is going wrong.

**Comment by tim-jenks** [comment]
Closing assuming resolved.
