### ISSUE TITLE
Add polyline or polygon with different elevation

### ISSUE THREAD

**Issue by cukingpro** [wrld3d/ios-api#40]
Hi,
I have some markers with different elevations. I want to draw polyline or polygon between these markers.
Does it support that?
Thank you

**Comment by ghost** [comment]
Yes, you can supply an array of elevations for the points in the line using the setPerPointElevations method.  Note that the default is for elevations to be relative to the terrain.  You can switch to using elevations above sea level if you prefer.  See https://www.wrld3d.com/ios/latest/docs/api/Classes/WRLDPolyline.html for all the docs.
