### ISSUE TITLE
Steps to integrate EEGEo sdk in existing app

### ISSUE THREAD

**Issue by Parveentyagi** [wrld3d/ios-api#7]
Hi Team,

I have search on git related to EEGEO sdk integration in existing iOS app. But i don't have found the complete and simple procedure to done it.
Every link show the process of download example app before it.

Please suggest me the right way to proceed further.

Thanks a lot.

**Comment by tim-jenks** [comment]
Duplicate https://github.com/eegeo/ios-api/issues/8 Closing
